benchmarks = '/Users/way/projects/bril/examples/test/tdce/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.tdce]
pipeline = [
  "bril2json",
  "python3 /Users/way/projects/bril/examples/tdce.py",
  "brili -p {args}",
]
